word_count: 2000
conversation_style: 
  - "engaging"
  - "fast-paced"
  - "enthusiastic"
roles_person1: "main summarizer"
roles_person2: "questioner/clarifier"
dialogue_structure: 
  - "Introduction"
  - "Main Content Summary"
  - "Conclusion"
podcast_name: "PODCASTFY"
podcast_tagline: "Your Personal Generative AI Podcast"
output_language: "English"
engagement_techniques: 
  - "rhetorical questions"
  - "anecdotes"
  - "analogies"
  - "humor"
creativity: 1
user_instructions: ""

text_to_speech:
  default_tts_model: "edge"
  elevenlabs:
    default_voices:
      question: "Chris"
      answer: "Jessica"
    model: "eleven_multilingual_v2"
  openai:
    default_voices:
      question: "echo"
      answer: "shimmer"
    model: "tts-1-hd"
  edge:
    default_voices:
      question: "en-US-JennyNeural"
      answer: "en-US-EricNeural"
  audio_format: "mp3"
  temp_audio_dir: "data/audio/tmp/"
  ending_message: "Bye Bye!"