conversation_style: 
  - "engaging"
  - "fast-paced"
  - "enthusiastic"
roles_person1: "main summarizer"
roles_person2: "questioner/clarifier"
dialogue_structure: 
  - "Introduction"
  - "Main Content Summary"
  - "Conclusion"
podcast_name: "Prompted by Podpod"
podcast_tagline: ""
output_language: "English"
engagement_techniques: 
  - "rhetorical questions"
  - "anecdotes"
  - "analogies"
  - "humor"
creativity: 1
user_instructions: "" # used as content type i.e newsletter, article
max_num_chunks: 8 # maximum number of rounds of discussions in longform
min_chunk_size: 600 # minimum number of characters to generate a round of discussion in longform

text_to_speech:
  default_tts_model: "gemini"
  output_directories:
    transcripts: "./data/transcripts"
    audio: "./data/audio"
  openai:
    default_voices:
      question: "echo"
      answer: "shimmer"
    model: "tts-1-hd"
  edge:
    default_voices:
      question: "en-US-JennyNeural"
      answer: "en-US-EricNeural"
  gemini:
    default_voices:
      question: "en-US-Journey-D"
      answer: "en-US-Journey-O"
  geminimulti:
    default_voices:
      question: "R"
      answer: "S"
      model: "en-US-Studio-MultiSpeaker"
  gemininew:
    default_voices:
      question: "Achird"
      answer: "Laomedeia"
    model: "gemini-2.5-flash-preview-tts"
  audio_format: "mp3"
  temp_audio_dir: "data/audio/tmp/"
  ending_message: ""
